#pragma once

enum TP_WINDOWSPATH_TYPE
{
	TP_WINDOWSPATH_RECYCLE				= CSIDL_BITBUCKET,//CSIDL_BITBUCKET   回收站
	TP_WINDOWSPATH_CONTROLS				= CSIDL_CONTROLS,// CSIDL_CONTROLS   控制面板
	TP_WINDOWSPATH_DESKTOP				= CSIDL_DESKTOP,// CSIDL_DESKTOP   Windows  桌面Desktop   
	TP_WINDOWSPATH_DESKTOPDIRECTORY		= CSIDL_DESKTOPDIRECTORY,// CSIDL_DESKTOPDIRECTORY   Desktop的目录  
	TP_WINDOWSPATH_DRIVES				= CSIDL_DRIVES,// CSIDL_DRIVES   我的电脑 
	TP_WINDOWSPATH_FONTS				= CSIDL_FONTS,// CSIDL_FONTS   字体目录  
	TP_WINDOWSPATH_NETHOOD				= CSIDL_NETHOOD,// CSIDL_NETHOOD   网上邻居  
	TP_WINDOWSPATH_NETWORK				= CSIDL_NETWORK,// CSIDL_NETWORK   网上邻居虚拟目录 
	TP_WINDOWSPATH_PERSONAL				= CSIDL_PERSONAL,// CSIDL_PERSONAL   我的文档
	TP_WINDOWSPATH_PRINTERS				= CSIDL_PRINTERS,// CSIDL_PRINTERS   打印机 
	TP_WINDOWSPATH_PROGRAMS				= CSIDL_PROGRAMS,// CSIDL_PROGRAMS   程序组  
	TP_WINDOWSPATH_RECENT				= CSIDL_RECENT,// CSIDL_RECENT   最近打开的文档 
	TP_WINDOWSPATH_SENDTO				= CSIDL_SENDTO,// CSIDL_SENDTO   “发送到”菜单项   
	TP_WINDOWSPATH_STARTMENU			= CSIDL_STARTMENU,// CSIDL_STARTMENU   任务条启动菜单项 
	TP_WINDOWSPATH_STARTUP				= CSIDL_STARTUP,// CSIDL_STARTUP   启动目录
	TP_WINDOWSPATH_TEMPLATES			= CSIDL_TEMPLATES,// CSIDL_TEMPLATES   文档模板  
};
AFX_EXT_API CString		   TP_GetWindowsSysPath(TP_WINDOWSPATH_TYPE eType);
AFX_EXT_API	void           File_FindFile(CString strPath,CString sFileName, BOOL bPath,CStringArray &aFile);
AFX_EXT_API CString        File_FindFile(CString strPath,GUID guidFind);
AFX_EXT_API void           File_FindFile(CString strPath,CString sType,CStringArray &aFile);
AFX_EXT_API BOOL           TP_FindFile(CString& sFindPath);
AFX_EXT_API void           TP_FindFileOnly(CString strPath,CStringArray &aFile);
AFX_EXT_API BOOL		   TP_GetStatus(LPCTSTR lpszFileName, CFileStatus& rStatus);



