

#pragma once


enum TP_SYSTEM_FONT
{
	FONT_BASE_TEXT,
	FONT_BASE_TEXT1,
	FONT_BASE_TEXT2,
	FONT_BASE_TEXT3,
	FONT_BASE_TEXT4,
	FONT_BASE_TEXT5,
	FONT_BASE_TEXT6,
	FONT_BASE_TEXT7,
	FONT_BASE_MAX,
};
enum TP_BRUSH_INDEX
{
	BRUSH_FRAME,	
	BRUSH_FRAME2,
	BRUSH_WINDOW,
	BRUSH_WINDOW2,	
#ifdef TP_NS_EDIT
	BRUSH_EDIT,
	BRUSH_EDITFOCUS,
	BRUSH_EDITREDONLY,
	BRUSH_CLIPTREE,
#endif
	BRUSH_MAX,
};

enum TP_BORDER_STYLE
{
	TP_BORDER_NORMAL = 1,
	TP_BORDER_FLAT,
	TP_BORDER_GROUPBOX,
	TP_BORDER_ROUNDCONRER,
	TP_BORDER_20040702,
	TP_BORDER_20090623,
};
enum TP_RES_COLOR
{
	COLOR_BASE_RES_DEF = 0,
	COLOR_BASE_RES_1 = 20,   
	COLOR_BASE_RES_2,      
	COLOR_BASE_RES_3,      
	COLOR_BASE_RES_4,      
	COLOR_BASE_RES_5,      
	COLOR_BASE_RES_6,      
	COLOR_BASE_RES_7,      
	COLOR_BASE_RES_8,      
	COLOR_BASE_RES_9,      
	COLOR_BASE_RES_10,     
	COLOR_BASE_RES_11,
	COLOR_BASE_RES_PREROLLOVEWRITE,
	COLOR_BASE_RES_PREROLLINSERT,
	COLOR_BASE_RES_MAX,    
};
enum TP_SYSTEM_COLOR
{
	COLOR_BASE_UNKNOW       = -1,
	//基本数据

	COLOR_BASE_BALCK        = 40,      //面色


	COLOR_BASE_FRAME,      //面色
	COLOR_BASE_FRAME2,
	
	COLOR_BASE_WINDOW,                 //底色
	COLOR_BASE_WINDOW2,

	COLOR_BASE_HIGHLIGHT,              //选种底色
	COLOR_BASE_HIGHLIGHT2,


	COLOR_BASE_3DLEFT,                 //边框
	COLOR_BASE_3DRIGHT,
	COLOR_BASE_3DLEFT2,
	COLOR_BASE_3DRIGHT2,

	COLOR_BASE_TEXT,                   //文本
	COLOR_BASE_TEXTFOCUS,
	COLOR_BASE_TEXTDIS,
	COLOR_BASE_TEXTHIGHLIGHT,

	//VU 表颜色 
	COLOR_VU_NORMAL,                  //正常
	COLOR_VU_ALARM,                   //警告
	COLOR_VU_DANGER,                  //危险
	COLOR_VU_DIVISION,                //分隔
	COLOR_VU_DISABLE,                 //分隔


	COLOR_TL_BEGIN,                 //时码
	COLOR_TL_TIMECODE,              //时码
	COLOR_TL_TIMECODECTL,
	COLOR_TL_TIMECODEBACK,          //时码
	//时间线有关数据	
	COLOR_TL_RECT,         //边框

	COLOR_TL_WNDBACK,
	COLOR_TL_HEADBACK,
	COLOR_TL_INOUT,

	COLOR_TL_HEADTEXTSEL,
	COLOR_TL_HEADTEXT,
	COLOR_TL_CLIPTEXTSEL,
	COLOR_TL_CLIPTEXT,
	COLOR_TL_VATEXT,

	COLOR_TL_HEAD,
	COLOR_TL_HEAD3DL,
	COLOR_TL_HEAD3DR,

	COLOR_TL_VHEAD,
	COLOR_TL_VHEAD3DL,
	COLOR_TL_VHEAD3DR,

	COLOR_TL_VTRHEAD,
	COLOR_TL_VTRHEAD3DL,
	COLOR_TL_VTRHEAD3DR,

	COLOR_TL_AHEAD,
	COLOR_TL_AHEAD3DL,
	COLOR_TL_AHEAD3DR,

	COLOR_TL_GHEAD,
	COLOR_TL_GHEAD3DL,
	COLOR_TL_GHEAD3DR,

	COLOR_TL_ACTTRACK,       //激活轨道
	COLOR_TL_VTRACK,         //视频
	COLOR_TL_VCLIP,
	COLOR_TL_VCLIP3DL,
	COLOR_TL_VCLIP3DR,

	COLOR_TL_VTRCLIP,
	COLOR_TL_VTRCLIP3DL,
	COLOR_TL_VTRCLIP3DR,


	COLOR_TL_PRECLIP,        //直通
	COLOR_TL_PRECLIP3DL,
	COLOR_TL_PRECLIP3DR,

	COLOR_TL_LAYTRACK,         //展开素材
	COLOR_TL_LAYCLIP,
	COLOR_TL_LAYCLIP3DL,
	COLOR_TL_LAYCLIP3DR,

	COLOR_TL_ATRACK,         //音频
	COLOR_TL_ACLIP,
	COLOR_TL_ACLIP3DL,
	COLOR_TL_ACLIP3DR,

	COLOR_TL_KTRACK,        //健
	COLOR_TL_KCLIP,
	COLOR_TL_KCLIP3DL,
	COLOR_TL_KCLIP3DR,

	COLOR_TL_ETRACK,        //特技
	COLOR_TL_ECLIP,
	COLOR_TL_ECLIP3DL,
	COLOR_TL_ECLIP3DR,

	COLOR_TL_GTRACK,        //字幕
	COLOR_TL_GCLIP,
	COLOR_TL_GCLIP3DL,
	COLOR_TL_GCLIP3DR,


	COLOR_TL_GCCLIP,         //字幕容器
	COLOR_TL_GCCLIP3DL,
	COLOR_TL_GCCLIP3DR,

	COLOR_TL_GSCLIP,         //字幕子时间线
	COLOR_TL_GSCLIP3DL,
	COLOR_TL_GSCLIP3DR,

	COLOR_TL_CCLIP,         //容器
	COLOR_TL_CCLIP3DL,
	COLOR_TL_CCLIP3DR,


	COLOR_TL_SCLIP,         //子时间线
	COLOR_TL_SCLIP3DL,
	COLOR_TL_SCLIP3DR,

	COLOR_TL_ICLIP,         //无效素材
	COLOR_TL_ICLIP3DL,
	COLOR_TL_ICLIP3DR,


	COLOR_TL_END,                 //时码


	COLOR_BASE_LIST,
	COLOR_CLIP_TEXT,
	COLOR_CLIP_TEXTFOCUS,
	COLOR_CLIP_TEXTDISABLE,
	COLOR_CLIP_BACK,
	COLOR_BASE_BACK,
	

	COLOR_CODE_TEXT,
	COLOR_CODE_TEXTFOCUS,
	COLOR_CODE_TEXTDIS,

	COLOR_CODE_BACK,
	COLOR_CODE_BACKDIS,

	COLOR_BLOCK_BACK,
	COLOR_TRIM_BACK,
	COLOR_TRIM_BACKDIS,
	COLOR_CODE_LINE,
	COLOR_CODE_LINEDIS,

	COLOR_CODE_UP,
	COLOR_CODE_DOWN1,
	COLOR_CODE_DOWN2,


	COLOR_LINE_SELCLIP,
	COLOR_LINE_WAVE,
	COLOR_LINE_LINE,
	COLOR_LINE_LINEEX,
	COLOR_LINE_LINESEEKEFF,
	COLOR_LINE_LINEFOCUS,
	COLOR_LINE_LINEDIS,

	COLOR_BAR_BACK,
	COLOR_BAR_BACKFOCUS,
	COLOR_BAR_BACKDIS,

	COLOR_LINE_TRACK,
	COLOR_LINE_SPLITBAR,

	COLOR_LINE_INOUT,
	COLOR_LINE_EXTRECT,
	COLOR_LINE_FX,
	COLOR_LINE_CLIPEDGETOP,
	COLOR_LINE_CLIPEDGEBOTTOM,

	COLOR_LINE_COMPOSE,
	COLOR_LINE_COMPOSEBACK,
	COLOR_LINE_REALBASE,
	COLOR_LINE_REALFALSE,
	COLOR_LINE_DARK,


	COLOR_LIST_TOP,
	COLOR_LIST_BOTTOM,
	COLOR_LIST_BACK1,	
	COLOR_LIST_BACK2,
	COLOR_LIST_BACK3,	

	COLOR_EFFLINE_DIS,	
	COLOR_EFFLINE_1,	
	COLOR_EFFLINE_2,	
	COLOR_EFFLINE_3,	
	COLOR_EFFLINE_4,	
	COLOR_EFFLINE_5,	
	COLOR_EFFLINE_6,
	COLOR_EFFLINE_7,
	COLOR_EFFLINE_8,

	COLOR_YELLOW,
	COLOR_RED,		
	COLOR_BLUE,
	COLOR_ORANGE,
	COLOR_WHITE,
	COLOR_BLACK,
	COLOR_GREEN,
	COLOR_0255255,

#ifdef TP_NS_EDIT
	COLOR_TL_IVCLIP,
	COLOR_TL_IVCLIP3DL,
	COLOR_TL_IVCLIP3DR,

	COLOR_TL_IACLIP,
	COLOR_TL_IACLIP3DL,
	COLOR_TL_IACLIP3DR,

	COLOR_TL_IGCLIP,
	COLOR_TL_IGCLIP3DL,
	COLOR_TL_IGCLIP3DR,

	COLOR_TL_IECLIP,
	COLOR_TL_IECLIP3DL,
	COLOR_TL_IECLIP3DR,

	COLOR_TL_IKCLIP,
	COLOR_TL_IKCLIP3DL,
	COLOR_TL_IKCLIP3DR,

	COLOR_TL_IHEADTEXT,
	COLOR_TL_TRACKMARK,              

	COLOR_CLIP_LIST,
	COLOR_CLIP_TREE,

	COLOR_BASE_TIMECODE,
	COLOR_BASE_EDIT,
	COLOR_BASE_EDITFOCUS,
	COLOR_BASE_EDITREDONLY,	
	COLOR_BASE_SELECTITEM,	
	COLOR_BASE_SELECTITEMA,	
	COLOR_LINE_WAVEA,
	COLOR_LINE_WAVEA1,
	COLOR_LINE_CLIPLEVEL,
	COLOR_LINE_CLIPLEVELACT,
	
	COLOR_TL_SYNCBREAK,
	COLOR_TL_SYNCBREAKSELECT,
	COLOR_TL_SYNCBREAKDIS,
#endif
	COLOR_MAX,

	COLOR_TL_AUDIOSCRUB = COLOR_GREEN,
};

AFX_EXT_API CFont    *TP_GetSysFont(TP_SYSTEM_FONT eFontIndex = FONT_BASE_TEXT);
AFX_EXT_API void      TP_GetSysColor(COLORREF *&pColor,long &lCount);
AFX_EXT_API void      TP_ReSetSysColor(TP_SYSTEM_COLOR dwBegin,TP_SYSTEM_COLOR dwEnd);

AFX_EXT_API COLORREF  TP_GetResColor(TP_RES_COLOR dwIndex,BOOL bSelect = FALSE,BOOL bActTrack = FALSE);
AFX_EXT_API COLORREF  TP_GetSysColor(TP_SYSTEM_COLOR dwIndex);
AFX_EXT_API COLORREF  TP_GetSysColor(UINT dwIndex);
AFX_EXT_API void      TP_SetSysColor(TP_SYSTEM_COLOR dwIndex,COLORREF clSet);
AFX_EXT_API void      TP_SetSysColor(UINT dwIndex,COLORREF clSet);
AFX_EXT_API HBRUSH    TP_GetSysBrush(TP_BRUSH_INDEX eBrushIndex);
AFX_EXT_API LPCTSTR	  TP_GetResColorName(TP_RES_COLOR dwIndex);

AFX_EXT_API void      TP_ResetSysFace();
AFX_EXT_API void      TP_ResetSysFont();
AFX_EXT_API void      TP_ResetSysColor();

AFX_EXT_API void      TP_InitSysGdi();
AFX_EXT_API void      TP_ReleaseSysGdi();
 